# Generated by Django 4.1 on 2024-05-15 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESTAURANT',
            fields=[
                ('resta_ID', models.AutoField(primary_key=True, serialize=False)),
                ('resta_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=1)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('tag', models.CharField(max_length=4)),
                ('more_Info', models.CharField(max_length=200)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.user')),
            ],
        ),
    ]
