# Generated by Django 4.1 on 2024-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_restaurant_image_restaurant_isopen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='image/404.png', upload_to='image/'),
        ),
    ]
