# Generated by Django 4.1 on 2024-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='404.png', null=True, upload_to='../media/restaurants/'),
        ),
    ]
