# Generated by Django 4.1 on 2024-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_comment_alter_restaurant_location_reply_manager_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
