# Generated by Django 4.1 on 2024-05-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_dish_tag_alter_restaurant_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='dishes/404.png', upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurants/404.png', upload_to='restaurants/'),
        ),
    ]
