# Generated by Django 4.1 on 2024-06-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_reply_comm_id_alter_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tag',
            field=models.CharField(blank=True, choices=[('S', 'Spicy'), ('SW', 'Sweet'), ('D', 'Drink'), ('N', 'Noodles'), ('F', 'Fast Food'), ('1', 'Good drink')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(blank=True, choices=[('S', 'Spicy'), ('SW', 'Sweet'), ('D', 'Drink'), ('N', 'Noodles'), ('F', 'Fast Food'), ('1', 'Good drink')], default='', max_length=4, null=True),
        ),
    ]
