# Generated by Django 4.1 on 2024-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_dish_tag_alter_restaurant_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(blank=True, choices=[('S', 'Spicy'), ('SW', 'Sweet'), ('D', 'Drink'), ('N', 'Noodles'), ('F', 'Fast Food'), ('1', 'Good drink'), ('C', 'Coffee')], default='', max_length=4, null=True),
        ),
    ]
