# Generated by Django 4.2.14 on 2024-07-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
    ]
